server:
  port: 8888

logging:
  level:
    ROOT: DEBUG

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/maddinenisri/centeralized-config
          clone-on-start: true
