service:
  kafka:
    host: ${KAFKA_HOST:kafka}
    port: 9092
    topic: test
    groupId: producer1
    offset: earliest
spring:
  cloud:
    stream:
      kafka:
        binder:
          brokers: ${KAFKA_HOST:kafka}:9092
          zkNodes: ${ZK_HOST:kafka-zk}
